import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const $=s=>document.querySelector(s), canvas=$('#scene'), viewer=$('#viewer'), loading=$('#loading');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x071018); scene.fog=new THREE.FogExp2(0x071018,.01);
const camera=new THREE.PerspectiveCamera(38,1,.1,120); camera.position.set(8.8,3.8,9.8);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.38; renderer.outputColorSpace=THREE.SRGBColorSpace;
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.dampingFactor=.06; controls.target.set(0,.9,0); controls.minDistance=5.5; controls.maxDistance=16; controls.maxPolarAngle=Math.PI*.52;
scene.add(new THREE.HemisphereLight(0xf8fcff,0x243344,4.4));
const dl=(c,i,p)=>{const l=new THREE.DirectionalLight(c,i);l.position.set(...p);scene.add(l);return l}; const pl=(c,i,d,p)=>{const l=new THREE.PointLight(c,i,d,1.6);l.position.set(...p);scene.add(l);return l};
const key=dl(0xffffff,6.8,[6,7,6]); key.castShadow=true; key.shadow.mapSize.set(2048,2048); dl(0xcceaff,3.5,[-7,4,8]); pl(0xf1fbff,20,25,[0,6,0]); pl(0xff7448,22,18,[-4,2.5,-3]); pl(0x6fddff,18,18,[4,3.5,-2]);
const floor=new THREE.Mesh(new THREE.CircleGeometry(12,96),new THREE.MeshStandardMaterial({color:0x111b26,roughness:.72,metalness:.18})); floor.rotation.x=-Math.PI/2; floor.position.y=-.78; floor.receiveShadow=true; scene.add(floor);
const ring=new THREE.Mesh(new THREE.RingGeometry(4.25,4.32,128),new THREE.MeshBasicMaterial({color:0xa56a4c,transparent:true,opacity:.72,side:THREE.DoubleSide})); ring.rotation.x=-Math.PI/2; ring.position.y=-.775; scene.add(ring);

const mats={
 shell:new THREE.MeshPhysicalMaterial({color:0xe4f1fa,metalness:.2,roughness:.06,transparent:true,opacity:.2,transmission:.78,ior:1.18,clearcoat:1,clearcoatRoughness:.02,side:THREE.DoubleSide,depthWrite:false}),
 glass:new THREE.MeshPhysicalMaterial({color:0xf0f8ff,metalness:.01,roughness:.02,transparent:true,opacity:.12,transmission:.99,thickness:.24,ior:1.15,side:THREE.DoubleSide,depthWrite:false}),
 frame:new THREE.MeshStandardMaterial({color:0x7f8b96,metalness:.88,roughness:.24}),
 engine:new THREE.MeshStandardMaterial({color:0xa4afb9,metalness:.82,roughness:.22}),
 dark:new THREE.MeshStandardMaterial({color:0x707b86,metalness:.8,roughness:.28}),
 metal:new THREE.MeshStandardMaterial({color:0xc0c8cf,metalness:.9,roughness:.2}),
 orange:new THREE.MeshStandardMaterial({color:0xf16338,metalness:.5,roughness:.25,emissive:0x301008,emissiveIntensity:.55}),
 cyan:new THREE.MeshStandardMaterial({color:0x79e3ff,metalness:.25,roughness:.18,emissive:0x0c4258,emissiveIntensity:.9}),
 brake:new THREE.MeshStandardMaterial({color:0xe45c3b,metalness:.5,roughness:.28}),
 rubber:new THREE.MeshStandardMaterial({color:0x101318,roughness:.75}),
 pipe:new THREE.MeshStandardMaterial({color:0x879099,metalness:.88,roughness:.25})
};
const car=new THREE.Group(); car.rotation.y=-.45; scene.add(car); const shell=[], parts=new Map(), pick=[], bases=new Map();
const reg=(o,id)=>{o.userData.part=id;pick.push(o);if(!parts.has(id))parts.set(id,[]);parts.get(id).push(o);return o};
const box=(parent,size,pos,mat,id)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);m.position.set(...pos);m.castShadow=m.receiveShadow=true;parent.add(m);if(id)reg(m,id);return m};
const cyl=(parent,r1,r2,h,pos,rot,mat,id)=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,24),mat);m.position.set(...pos);m.rotation.set(...rot);m.castShadow=m.receiveShadow=true;parent.add(m);if(id)reg(m,id);return m};
const base=(o,e)=>bases.set(o,{p:o.position.clone(),e:new THREE.Vector3(...e)});
const body=(size,pos,mat=mats.shell,id)=>{const m=box(car,size,pos,mat,id);shell.push(m);return m};

box(car,[5.7,.22,2.95],[-.1,.25,0],mats.frame);
body([2.1,.17,2.55],[1.85,1.02,0],mats.glass,'engine'); body([2.2,.92,2.25],[-.25,1.25,0],mats.glass,'steering'); body([2.2,.12,2.15],[-.38,1.78,0]); body([1.55,.33,2.45],[-2.22,.8,0]); body([.42,.5,2.75],[2.95,.38,0]); body([.38,.48,2.7],[-2.95,.38,0]); for(const z of [-1.32,1.32])body([5.3,.45,.14],[0,.72,z]); for(const z of [-1.42,1.42])body([3.9,.24,.16],[-.35,.32,z]);

const eng=new THREE.Group(); eng.position.set(1.1,.56,0); car.add(eng); base(eng,[.35,.95,0]); box(eng,[1.2,.62,1.25],[0,0,0],mats.engine,'engine');
for(const s of [-1,1]){box(eng,[1,.24,.34],[0,.42,s*.44],mats.dark,'engine');for(let i=0;i<4;i++){const x=-.4+i*.27;cyl(eng,.095,.095,.19,[x,.05,s*.22],[Math.PI/2,0,0],mats.metal,'pistons');cyl(eng,.025,.025,.28,[x,-.12,s*.15],[Math.PI/2,0,0],mats.metal,'pistons')}}
cyl(eng,.075,.075,1.1,[0,-.23,0],[Math.PI/2,0,0],mats.orange,'crankshaft'); for(let i=0;i<5;i++)box(eng,[.17,.23,.1],[-.44+i*.22,-.23,0],mats.orange,'crankshaft'); cyl(eng,.16,.22,.92,[0,.68,0],[0,0,Math.PI/2],mats.metal,'engine');
for(const z of [-.7,.7]){const t=new THREE.Mesh(new THREE.TorusGeometry(.2,.07,14,30),mats.orange);t.position.set(.24,.32,z);t.rotation.x=Math.PI/2;t.castShadow=true;eng.add(t);reg(t,'turbo')}
const rad=box(car,[.12,.72,1.55],[2.45,.56,0],mats.dark,'radiator');base(rad,[.55,.15,0]);for(let i=-6;i<=6;i++)box(car,[.03,.55,.035],[2.39,.56,i*.11],mats.metal);
const trans=new THREE.Group();trans.position.set(.2,.28,0);car.add(trans);base(trans,[0,.55,0]);cyl(trans,.36,.24,.95,[0,0,0],[0,0,Math.PI/2],mats.dark,'transmission');const shaft=cyl(car,.05,.05,2.45,[-1.55,-.02,0],[0,0,Math.PI/2],mats.metal,'transmission');base(shaft,[0,-.25,0]);const diff=new THREE.Mesh(new THREE.SphereGeometry(.3,24,16),mats.dark);diff.position.set(-2.6,-.02,0);diff.scale.set(1.25,.78,1);car.add(diff);reg(diff,'transmission');
const rack=cyl(car,.042,.042,1.75,[1.95,.16,0],[Math.PI/2,0,0],mats.cyan,'steering');base(rack,[0,.35,0]);for(const z of [-1,1])cyl(car,.024,.024,.74,[1.95,.16,z*.92],[Math.PI/2,0,0],mats.cyan,'steering');const sw=new THREE.Mesh(new THREE.TorusGeometry(.24,.03,12,28),mats.dark);sw.position.set(-.05,1.18,-.63);sw.rotation.set(0,.35,Math.PI/2);car.add(sw);reg(sw,'steering');
for(const z of [-.5,.5]){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(1.25,.3,z),new THREE.Vector3(.7,.1,z),new THREE.Vector3(-.4,-.28,z),new THREE.Vector3(-2.5,-.28,z)]);const p=new THREE.Mesh(new THREE.TubeGeometry(curve,48,.05,10,false),mats.pipe);car.add(p);reg(p,'exhaust');base(p,[0,-.2,z*.35]);box(car,[.68,.2,.28],[-2.58,-.25,z*.68],mats.pipe,'exhaust');cyl(car,.07,.07,.42,[-3.08,-.19,z*.82],[0,0,Math.PI/2],mats.pipe,'exhaust')}

const wheels=[[2.06,.02,1.48],[2.06,.02,-1.48],[-2.1,.02,1.48],[-2.1,.02,-1.48]]; wheels.forEach(([x,y,z],i)=>{const g=new THREE.Group();g.position.set(x,y,z);car.add(g);base(g,[0,0,z>0?.35:-.35]);const tire=cyl(g,.62,.62,.42,[0,0,0],[0,0,Math.PI/2],mats.rubber,'tires');const rim=cyl(g,.34,.34,.18,[0,0,0],[0,0,Math.PI/2],mats.metal,'tires');const disc=cyl(g,.38,.38,.09,[0,0,0],[0,0,Math.PI/2],mats.metal,'brakes');box(g,[.18,.26,.16],[0,.26,.16],mats.brake,'brakes');cyl(car,i<2?.06:.055,i<2?.06:.055,i<2?.82:.72,[x+(i<2?-.15:.18),.52,z],[0,0,Math.PI/2],mats.cyan,'suspension')});
const white=new THREE.MeshStandardMaterial({color:0xffffff,emissive:0xc9edff,emissiveIntensity:3}),red=new THREE.MeshStandardMaterial({color:0xff5338,emissive:0xff2208,emissiveIntensity:2.6});for(const z of [-.9,.9])box(car,[.16,.14,.64],[3.2,.72,z],white);for(const z of [-.9,.9])box(car,[.16,.14,.6],[-3.18,.72,z],red);

const info={engine:['POWERTRAIN / 01','Twin-Turbo V8 Engine','A transparent body reveals the V8 engine, pistons, crankshaft, intake and turbochargers working together to create torque.',['LAYOUT','V8','BOOST','Twin Turbo']],transmission:['DRIVETRAIN / 02','Transmission','The gearbox changes ratios and transfers engine torque through the driveshaft to the differential.',['TYPE','8-Speed','ROLE','Torque control']],brakes:['CHASSIS / 03','Disc Brakes','Calipers squeeze pads against the brake discs to convert motion into heat and slow the vehicle.',['TYPE','Ventilated disc','CONTROL','ABS']],suspension:['CHASSIS / 04','Independent Suspension','Springs and dampers keep the tires controlled while isolating the body from bumps.',['FRONT','Independent','DAMPING','Adaptive']],steering:['CHASSIS / 05','Rack & Pinion Steering','The steering rack and tie rods convert steering input into front-wheel angle.',['TYPE','Rack & pinion','ASSIST','Electric']],exhaust:['ENGINE / 06','Exhaust System','Exhaust gases flow from the engine through pipes and mufflers before exiting at the rear.',['FLOW','Engine to tailpipe','ROLE','Gas management']],pistons:['ENGINE INTERNALS','Pistons & Connecting Rods','Pistons move inside the cylinders and transfer combustion force to the crankshaft.',['MOTION','Reciprocating','COUNT','8']],crankshaft:['ENGINE INTERNALS','Crankshaft','The crankshaft converts piston motion into rotation.',['ROLE','Rotation','LINK','Drivetrain']],turbo:['AIR SYSTEM','Turbochargers','Turbochargers use exhaust energy to compress intake air and increase power density.',['DRIVE','Exhaust gas','OUTPUT','Boost']],radiator:['COOLING','Radiator','The radiator removes heat from engine coolant.',['FLUID','Coolant','ROLE','Heat rejection']],tires:['ROAD CONTACT','Performance Tires','Tires provide the contact patch for acceleration, braking and cornering.',['ROLE','Traction','TYPE','Radial']]};
let selected='engine',exploded=false,xray=true,auto=false;const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();
function panel(id){selected=info[id]?id:'engine';const d=info[selected];$('#infoKicker').textContent=d[0];$('#infoTitle').textContent=d[1];$('#infoText').textContent=d[2];$('#specGrid').innerHTML=`<div><small>${d[3][0]}</small><strong>${d[3][1]}</strong></div><div><small>${d[3][2]}</small><strong>${d[3][3]}</strong></div>`;$('#infoCard').classList.remove('hidden');document.querySelectorAll('.system').forEach(b=>b.classList.toggle('active',b.dataset.part===selected))}
function focus(id){const a=parts.get(id)||[];if(!a.length)return;const b=new THREE.Box3();a.forEach(o=>b.expandByObject(o));const c=b.getCenter(new THREE.Vector3()),s=b.getSize(new THREE.Vector3()).length();controls.target.copy(c);const d=camera.position.clone().sub(c).normalize();camera.position.copy(c.clone().add(d.multiplyScalar(Math.max(4.8,s*2.2))))}
function xr(on){shell.forEach(p=>{const g=p.material===mats.glass;p.material.opacity=on?(g?.12:.2):(g?.42:.8);if('transmission'in p.material)p.material.transmission=on?(g?.99:.78):(g?.4:.08);p.material.needsUpdate=true})}
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);canvas.style.cursor=ray.intersectObjects(pick,true)[0]?'pointer':'grab'});
canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const h=ray.intersectObjects(pick,true)[0];if(h){let o=h.object;while(o&&!o.userData.part)o=o.parent;if(o){panel(o.userData.part);focus(o.userData.part)}}});
document.querySelectorAll('.system').forEach(b=>b.addEventListener('click',()=>{panel(b.dataset.part);focus(b.dataset.part)}));$('#focusBtn').addEventListener('click',()=>focus(selected));$('#closeCard').addEventListener('click',()=>$('#infoCard').classList.add('hidden'));$('#resetView').addEventListener('click',()=>{camera.position.set(8.8,3.8,9.8);controls.target.set(0,.9,0)});$('#autoRotateBtn').addEventListener('click',()=>{auto=!auto;controls.autoRotate=auto;$('#autoRotateBtn').classList.toggle('active',auto)});$('#explodeBtn').addEventListener('click',e=>{exploded=!exploded;e.currentTarget.classList.toggle('active',exploded)});$('#xrayBtn').addEventListener('click',e=>{xray=!xray;xr(xray);e.currentTarget.classList.toggle('active',xray)});
function resize(){const w=viewer.clientWidth,h=viewer.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}window.addEventListener('resize',resize);resize();xr(true);panel('engine');
const clock=new THREE.Clock();function loop(){requestAnimationFrame(loop);controls.update();bases.forEach((b,o)=>o.position.lerp(b.p.clone().add(exploded?b.e:new THREE.Vector3()),.08));ring.material.opacity=.52+Math.sin(clock.getElapsedTime()*1.2)*.08;renderer.render(scene,camera)}loop();setTimeout(()=>loading.classList.add('done'),450);
