import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/loaders/GLTFLoader.js';
const viewport=document.getElementById('viewport'),loaderEl=document.getElementById('loader');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x07101a); scene.fog=new THREE.FogExp2(0x07101a,.032);
const camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.01,500); camera.position.set(9,4.4,11);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(viewport.clientWidth,viewport.clientHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.25; renderer.shadowMap.enabled=true; viewport.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.dampingFactor=.06; controls.autoRotate=true; controls.autoRotateSpeed=.8; controls.minDistance=4; controls.maxDistance=24; controls.target.set(0,.8,0);
scene.add(new THREE.HemisphereLight(0xcfeaff,0x07101a,2.8)); const key=new THREE.DirectionalLight(0xffffff,4); key.position.set(6,10,7); key.castShadow=true; scene.add(key); const blue=new THREE.PointLight(0x2caeff,50,20,2); blue.position.set(-4,3,4); scene.add(blue); const red=new THREE.PointLight(0xff3344,24,16,2); red.position.set(5,1,-4); scene.add(red);
const floor=new THREE.Mesh(new THREE.CircleGeometry(12,96),new THREE.MeshStandardMaterial({color:0x07111b,metalness:.55,roughness:.28})); floor.rotation.x=-Math.PI/2; floor.receiveShadow=true; floor.position.y=-.02; scene.add(floor); const grid=new THREE.GridHelper(24,24,0x15466a,0x0b2335); grid.position.y=.002; scene.add(grid);
const systems=[['Engine','⚙','Power & combustion'],['Transmission','⇄','Transfers torque'],['Suspension','⌁','Ride & control'],['Braking','◉','Stopping force'],['Steering','↻','Direction control'],['Electrical','ϟ','Power network'],['Cooling','❄','Heat management'],['Exhaust','≋','Gas flow'],['Fuel','⛽','Fuel delivery'],['Body','◇','Structure & shell']];
const sysWrap=document.getElementById('systems'); systems.forEach((s,i)=>{const b=document.createElement('button');b.className='sys'+(i===0?' active':'');b.innerHTML=`<span class="ico">${s[1]}</span><small>${s[0]}</small>`;b.onclick=()=>selectSystem(i,b);sysWrap.appendChild(b)});
let car,meshes=[],original=new Map(),selected=null; const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();
function fit(root){const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()); root.position.sub(center); const scale=7/Math.max(size.x,size.y,size.z); root.scale.setScalar(scale); const box2=new THREE.Box3().setFromObject(root); root.position.y-=box2.min.y; controls.target.set(0,1.15,0); camera.position.set(9,4.7,11); controls.update();}
function tune(root){root.traverse(o=>{if(!o.isMesh)return; meshes.push(o); o.castShadow=o.receiveShadow=true; const mats=Array.isArray(o.material)?o.material:[o.material]; mats.forEach(m=>{if(!m)return; m.side=THREE.DoubleSide; const n=(m.name||'').toLowerCase(); if(n.includes('glass')){m.transparent=true;m.opacity=.22;m.roughness=.08;m.metalness=.05;m.depthWrite=false}else if(n.includes('tire')||n.includes('black')){m.roughness=.5}else if(n.includes('paint')||n.includes('metal')||n.includes('steel')||n.includes('alum')){m.metalness=.65;m.roughness=.24} original.set(m,{opacity:m.opacity,transparent:m.transparent,depthWrite:m.depthWrite,color:m.color?.clone(),emissive:m.emissive?.clone(),emissiveIntensity:m.emissiveIntensity||0})})})}
new GLTFLoader().load('./assets/models/r8-car.glb',g=>{car=g.scene; fit(car); tune(car); scene.add(car); loaderEl.classList.add('hide'); setTimeout(()=>loaderEl.remove(),600)},undefined,e=>{console.error(e);loaderEl.querySelector('b').textContent='3D model failed to load';loaderEl.style.background='#180909'});
function describe(name){const n=(name||'').toLowerCase(); if(n.includes('glass'))return['Glass / Windows','Transparent glazing material.','◫']; if(n.includes('tire'))return['Tire','High-friction rubber contact surface.','◉']; if(n.includes('paint'))return['Body / Painted Surface','Exterior painted vehicle surface.','◇']; if(n.includes('steel')||n.includes('alum')||n.includes('metal'))return['Metal Component','Structural or mechanical metallic component.','⚙']; if(n.includes('interior')||n.includes('cloth'))return['Interior','Cabin trim and interior component.','▣']; return[name||'Vehicle Part','3D component selected directly from the uploaded model.','⚙']}
function setInfo(title,desc,ico='⚙'){document.getElementById('partTitle').textContent=title;document.getElementById('partDesc').textContent=desc;document.getElementById('partIcon').textContent=ico}
renderer.domElement.addEventListener('pointerdown',ev=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=((ev.clientX-r.left)/r.width)*2-1;mouse.y=-((ev.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(meshes,false)[0];if(!hit)return; selected=hit.object;const mat=Array.isArray(selected.material)?selected.material[0]:selected.material;const d=describe(mat?.name||selected.name);setInfo(...d);if(mat?.emissive){mat.emissive.setHex(0x0878bb);mat.emissiveIntensity=.8;setTimeout(()=>{const o=original.get(mat);if(o){mat.emissive.copy(o.emissive||new THREE.Color(0));mat.emissiveIntensity=o.emissiveIntensity}},700)}});
function selectSystem(i,b){document.querySelectorAll('.sys').forEach(x=>x.classList.remove('active'));b.classList.add('active');const s=systems[i];setInfo(s[0],s[2]+' — use the 3D model to inspect the corresponding vehicle area.',s[1]);const angles=[[7,3.5,9],[8,3,5],[8,2.5,-7],[7,2.2,-8],[5,4,9],[-7,4,8],[-8,3,4],[-7,2,-8],[-5,3,8],[9,4,11]];const a=angles[i];camera.position.set(...a);controls.target.set(0,1.1,0);controls.update()}
let xray=false;document.getElementById('xrayBtn').onclick=e=>{xray=!xray;e.currentTarget.classList.toggle('active',xray);document.getElementById('modeText').textContent=xray?'X‑Ray':'Exterior';meshes.forEach(m=>{const mats=Array.isArray(m.material)?m.material:[m.material];mats.forEach(mat=>{const o=original.get(mat);if(!o)return;const n=(mat.name||'').toLowerCase(),body=n.includes('paint')||n.includes('glass')||n.includes('black');if(xray&&body){mat.transparent=true;mat.opacity=n.includes('glass')?.08:.18;mat.depthWrite=false}else{mat.transparent=o.transparent;mat.opacity=o.opacity;mat.depthWrite=o.depthWrite}})})};
document.getElementById('rotateBtn').onclick=e=>{controls.autoRotate=!controls.autoRotate;e.currentTarget.classList.toggle('active',controls.autoRotate)};document.getElementById('resetBtn').onclick=()=>{camera.position.set(9,4.7,11);controls.target.set(0,1.15,0);controls.update()};document.getElementById('exploreBtn').onclick=()=>{controls.autoRotate=false;document.getElementById('rotateBtn').classList.remove('active');camera.position.set(7,3,8);controls.update()};
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}addEventListener('resize',resize);resize();
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}animate();